name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    # Install test-reporter
    - run:  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run:  chmod +x ./cc-test-reporter
      # before build step
    - run: ./cc-test-reporter before-build
      # RUN TEST HERE
    - run: go test ./... -coverprofile c.out
      # after build step
    - run: ./cc-test-reporter after-build --prefix=github.com/sgaunet/tcbs
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
